Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'; Import-Module (Join-Path $PSScriptRoot 'CheckoutTimingCorrelation.psm1') -Force
$assertions=0; function Assert-Equal($Actual,$Expected,[string]$Message){$script:assertions+=1;if($Actual -ne $Expected){throw "$Message actual=$Actual expected=$Expected"}}
function New-Summary([string]$RunId,[int]$Rate,[double]$Acquire,[double]$Db){[pscustomobject]@{ValidMeasurement=$true;Run=[pscustomobject]@{Id=$RunId;Scenario='distributed';RatePerSecond=$Rate;DurationSeconds=10};Fixture=[pscustomobject]@{TotalSeats=2000;PreparedBeforeSampling=$true};K6=[pscustomobject]@{Result=[pscustomobject]@{schemaVersion=2;iterations=10;droppedIterations=0;checkoutConfirmed=10;expectedContention=0;unexpectedNonSuccessful=0;unexpectedFailureRate=0;checkoutDurationMs=[pscustomobject]@{p95=10};maxObservedVus=10;maxAllocatedVus=100;preAllocatedVus=100;configuredMaxVus=200};FinalSnapshot=[pscustomobject]@{invariantSatisfied=$true;reservedSeats=10;reservations=10;bookings=10;payments=10};TransitionDelta=[pscustomobject]@{reservationConfirmed=10;verificationClaimed=10}};Metrics=[pscustomobject]@{Peaks=[pscustomobject]@{HikariPending=0;DbRowLockCurrentWaits=0};Deltas=[pscustomobject]@{DbRowLockWaits=0;DbRowLockTimeMs=0;DbDeadlocks=0}};HikariAcquire=[pscustomobject]@{AcquireCount=10;AcquireWaitMilliseconds=$Acquire;AverageAcquireWaitMilliseconds=($Acquire/10);TimeoutCount=0};StatementDiagnostics=[pscustomobject]@{StatementCount=10;ExecutionMilliseconds=$Db;LockMilliseconds=($Db/2);TopStatements=@()}}}
$records=foreach($rate in 50,75,100){foreach($repeat in 1..3){$id="i136-$rate-$repeat";[pscustomobject]@{Rate=$rate;Warmup=$false;RunId=$id;Summary=(New-Summary $id $rate (100+$rate+$repeat) (200+$rate+$repeat))}}}
$aggregate=@(New-CheckoutTimingCorrelationAggregate $records)
Assert-Equal $aggregate.Count 3 'All rates aggregate.'; Assert-Equal $aggregate[0].Metrics.HikariAcquireWaitMilliseconds.Median 152 'Acquire wait median aggregates.'; Assert-Equal $aggregate[2].Metrics.DbStatementExecutionMilliseconds.Median 302 'Statement time median aggregates.'
$runner=Get-Content -Raw -Encoding utf8 (Join-Path $PSScriptRoot 'Run-CheckoutTimingCorrelation.ps1')
Assert-Equal ($runner.Contains('Restore-CheckoutBaselineMariaDb')) $true 'Diagnostic runner must restore baseline MariaDB.'
Assert-Equal ($runner.Contains('trap { Restore-CheckoutBaselineMariaDb')) $true 'Diagnostic runner must restore baseline after failures.'
Write-Output "CHECKOUT_TIMING_CORRELATION_TESTS_PASSED assertions=$assertions"
